name             'cerkberk1'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cerkberk1'
long_description 'Installs/Configures cerkberk1'
version          '0.1.0'
